title: Research Impact Reporting
author: Digital Research Services
copyright: "2026"

repository:
  url: https://github.com/vvlooking/research-impact
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  extra_css:
    - _static/custom.css
